[system]
device=AlphaLab
mac=6c:ec:eb:ff:d9:72

[recording]
numchan=1
channel=10385
fs=44000
save=true
savepath=./data/DualThresholds/

[stimulation]
numchan=1
stimchan=10004
retnchan=10000

[cleandbs]
enable=true
threshold=1000
precut=0.0002
postcut=0.003
downsample=256

[filter]
enable=false
downsample=0
sosmat= 

[parameter]
;Sampling rate, should match the settings in [cleandbs] & [filter]
fs=256;

;Frequency band of target oscillation
;unit: Hz
freqband="13,35"

;Initial stimulation parameters
;unit: mA
amplitude=0.05
;unit: ms
pulsewidth=0.06
;unit: Hz
frequency=130

;Stimulation amplitude limitations
amplmax=0.1
amplmin=0.01

;Stimulation amplitude adjustion
;IMPORTANT: high adjustion rate may cause side effects
;unit: mA
adjuststep=0.01
;unit: point
adjustwindow=256

;When the ninit=0, the thresholds are set as the absolute values
;of the thrUpper and thrLower.
;When the ninit>0, the thresholds are set based on the first 
;ninit window data.
;1.Segment the initial data based on 'adjustwindow'
;2.Calculate the target oscillation amplitudes of each window
;3.thrUpper(%) windows' amplitudes smaller than the upper threshold
;4.thrLower(%) windows' amplitudes smaller than the lower threshold

;unit: window
ninit=300
thrUpper=0.75
thrLower=0.25

savepath=./data/DualThresholds/
