[system]
device=AOTest
mac=6c:ec:eb:ff:eb:0f

[recording]
numchan=1
channel=10385
fs=44000
save=true
savepath=./data/AmplModulation/

[stimulation]
numchan=1
stimchan=10000
retnchan=10008

[cleandbs]
enable=true
threshold=1000
precut=0.0002
postcut=0.005
downsample=300

[filter]
enable=false
downsample=0
sosmat= 

[parameter]
;Sampling rate, should match the settings in [cleandbs] & [filter]
fs=300;

;Frequency band of target oscillation
;unit: Hz
freqband="13,35"

;Initial stimulation parameters
;unit: mA
amplitude=0.05
;unit: ms
pulsewidth=0.06
;unit: Hz
frequency=130

;Stimulation amplitude limitations
amplmax=0.2
amplmin=0

;Max adjustion rate of DBS amplitude
;unit: mA
maxrate=0.05

;Adjust window length
;unit: point
adjustwindow=300

;Parameters of the linear modulation
;S=A*X+B, S:stimulation amplitude, X:target oscillation amplitude
;If ninit>0: A&B will be set automatically
;1.Caching the initial ninit windows of data
;2.Calculate the max & min amplitudes of target oscillation
;3,The parameters of A&B are set to match the range of target
;oscillation and the stimulation amplitude limitations
;If ninit<=0: set A&B manually
ninit=30;
A=
B=

;Data saving path
savepath=./data/AmplModulation/
