function plotnsdbsdata(datapath, filedate, node, section)
%PLOTNSDBSDATA Plot NSDBS data, NSDBS data are the .txt files generated by
%the dns-qt function or iDBS-trp function.
%  Use as:
%    plotnsdbsdata(datapath, filedate, node, section);
%  Input:
%    datapath, the path of NSDBS data
%    filedate, time stamp of the NSDBS data, or 'latest'
%    node, the target node of wpt tree
%    section, the time section of interest
%
%  Author: Yingnan Nie
%  Date: Feb 13th, 2020

%% Load NDDBS data
[raw, filt, coef, state, thr, info] = readnsdbsdata(datapath, filedate);
state = [0; state];
state(end) = [];

step = info.step;
fs = 44000;
win = info.win;

%% Align time axis
raw = reshape(raw', numel(raw), 1);
raw = raw(~isnan(raw));

fsfilt = numel(filt)/numel(raw)*fs;
%fsfilt = info.fswpt;

time = 1/fs:1/fs:length(raw)/fs;

filt = reshape(filt', numel(filt), 1);
timeFilt = 1/fsfilt:1/fsfilt:length(filt)/fsfilt;

state = repmat(state, 1, step);
state = reshape(state', numel(state), 1);

nCoefWin = size(coef,2);
nCoefStep = ceil(nCoefWin/win*step);
coefStep = coef(:,end-nCoefStep+1:end);
coefStep = reshape(coefStep', numel(coefStep), 1);
fsCoefStep = fsfilt*nCoefStep/step;
timeCoefStep = 1/fsCoefStep:1/fsCoefStep:length(coefStep)/fsCoefStep;

coef = reshape(coef', numel(coef), 1);
fsCoef = fsfilt*nCoefWin/step;
timeCoef = 1/fsCoef:1/fsCoef:length(coef)/fsCoef;

thrWin = repmat(thr, 1, nCoefWin);
thrWin = reshape(thrWin', numel(thrWin), 1);

thrStep = repmat(thr, 1, nCoefStep);
thrStep = reshape(thrStep', numel(thrStep), 1);

%% Offline replay
% Extract coefficients

dLevel = node(1);
basis = 'sym4';
entropy = 'shannon';

nCoefOff = ceil(length(filt)/(2^dLevel));
wpTree = wpdec(filt, dLevel, basis, entropy);
coefOff = wpcoef(wpTree, node);

% Reconstruct signal
recn = wprcoef(wpTree, node);

coefOff = selectcoefs(coefOff, nCoefOff);
fsCoefOff = fsfilt/2^node(1);
timeCoefOff = 1/fsCoefOff:1/fsCoefOff:length(coefOff)/fsCoefOff;

%% Plot
% Segment data
idx = time>section(1)&time<section(2);
time = time(idx);
time = time-time(1);
raw = raw(idx);

idx = timeFilt>section(1)&timeFilt<section(2); 
timeFilt = timeFilt(idx);
timeFilt = timeFilt-timeFilt(1);
filt = filt(idx);
recn = recn(idx);
state = state(idx);

idx = timeCoef>section(1)&timeCoef<section(2); 
timeCoef = timeCoef(idx);
timeCoef = timeCoef-timeCoef(1);
coef = coef(idx);
thrWin = thrWin(idx);

idx = timeCoefStep>section(1)&timeCoefStep<section(2); 
timeCoefStep = timeCoefStep(idx);
coefStep = coefStep(idx);
thrStep = thrStep(idx);

fig = figure;
axes = get(gcf,'children');

% Raw signal 
subplot(511);
plot(time, raw);
%set(gca, 'FontSize', 16);
title('Raw Signal');

% Filtered signal
subplot(512);
plot(timeFilt, filt);
%set(gca, 'FontSize', 16);
title('Filtered Signal');

% WPT Coefficients (Offline)
% subplot(613);
% plot(timeCoefOff, coefOff);
% set(gca, 'FontSize', 16);
% title('Wavelet Coefficients (offline)');
% set(gca, 'XLim', section);

% Reconstructed Signal (Offline)
subplot(513);
plot(timeFilt, recn);
%set(gca, 'FontSize', 16);
title('Offline Reconstructed Signal');

% % WPT coefficients (Windowed)
% subplot(514);
% hold on;
% plot(timeCoef, coef);
% plot(timeCoef, thrWin, 'r');
% plot(timeCoef, -thrWin, 'r')
% hold off;
% %set(gca, 'FontSize', 16);
% title('Wavelet Coefficients(online)');
% set(gca, 'XLim', section);

% WPT coefficients (Windowed)
subplot(514);
hold on;
plot(timeCoefStep, coefStep);
plot(timeCoefStep, thrStep, 'r');
plot(timeCoefStep, -thrStep, 'r')
hold off;
%set(gca, 'FontSize', 16);
title('Real-time Wavelet Coefficients');

% Detected state
subplot(515);
plot(timeFilt, state);
set(gca, 'YLim', [-0.2, 1.2]);
%set(gca, 'FontSize', 16);
title('Stimulation State');

set(fig,'windowkeypressfcn',@keypressfcn);

end

function keypressfcn(~,evt)
    axes = get(gcf,'children');
    x = get(axes(1),'XLim');
    
    key = evt.Key;
    switch key
        case 'uparrow'
            lim = [x(1), x(1)+(x(2)-x(1))*0.9];
            for i=1:length(axes)
                set(axes(i), 'XLim', lim);
            end
        case 'downarrow'
            lim = [x(1), x(1)+(x(2)-x(1))*1.1];
            for i=1:length(axes)
                set(axes(i), 'XLim', lim);
            end
        case 'leftarrow'
        	lim = x-(x(2)-x(1))/10;
            for i=1:length(axes)
                set(axes(i), 'XLim', lim);
            end
        case 'rightarrow'
            lim = x+(x(2)-x(1))/10;
            for i=1:length(axes)
                set(axes(i), 'XLim', lim);
            end
    end

end