function [raw, filt, coef, state, thr, info] = readnsdbsdata(datapath, filedate)
%PLOTNSDBSDATA Plot NSDBS data, NSDBS data are the .txt files generated by
%the dns-qt function or iDBS-trp function.
%  Use as:
%    [raw, filt, coef, state, thr, info] = readnsdbsdata(datapath, filedate);
%  Input:
%    datapath, the path of NSDBS data
%    filedate, the date of NSDBS data or 'latest'
%  Output:
%    raw, raw siganl
%    filted, filtered siganl (downsampe to fswpt)
%    coef, WPT coefs
%    state, detected states
%    thr, adaptive threshold
%    info, information
%
%  Author: Yingnan Nie
%  Date: Feb 6th, 2020

%% Get time stamp
if isequal(filedate,'latest')
    formatSpec = '%s%[^\n\r]';
    fileID = fopen(fullfile(datapath, 'latestfile.txt'),'r');
    timeStamp = textscan(fileID, formatSpec, 'Delimiter', '', 'TextType', 'string',  'ReturnOnError', false);
    timeStamp = timeStamp{1};
    fclose(fileID);
else
    timeStamp = filedate;
end

%% Read info
formatSpec = '%s%f';
fileID = fopen(fullfile(datapath, strcat('INFO-',timeStamp,'.txt')),'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', '\t', 'TextType', 'string', 'HeaderLines' ,3, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);
info = struct(dataArray{1}(1),dataArray{2}(1),...
              dataArray{1}(2),dataArray{2}(2),...
              dataArray{1}(3),dataArray{2}(3),...
              dataArray{1}(4),dataArray{2}(4),...
              dataArray{1}(5),dataArray{2}(5));

%% Read data
DELIMITER = '\t';
temp = importdata(fullfile(datapath, strcat('RAW-',timeStamp,'.txt')));
raw = temp;

temp = importdata(fullfile(datapath, strcat('DWNSMP-',timeStamp,'.txt')), DELIMITER);
filt = temp.data;

temp = importdata(fullfile(datapath, strcat('CFS-',timeStamp,'.txt')), DELIMITER);
coef = temp.data;

delimiter = '\t';
formatSpec = '%*q%*q%*q%*q%f%[^\n\r]';
fileID = fopen(fullfile(datapath, strcat('STATE-',timeStamp,'.txt')),'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);
fclose(fileID);
state = [dataArray{1:end-1}];

temp = importdata(fullfile(datapath, strcat('THR-',timeStamp,'.txt')), DELIMITER);
thr = temp.data;

end

